from typing import List, Optional
from pydantic import BaseModel, Field


class Task(BaseModel):
    """
    Represents a single actionable task under a story
    """

    title: str = Field(..., description="Task title or description")


class Story(BaseModel):
    """
    Represents a backlog story created from meeting discussions
    """

    title: str = Field(..., description="Story title")

    description: Optional[str] = Field(
        default="",
        description="Detailed description of the story"
    )

    priority: Optional[str] = Field(
        default="medium",
        description="Story priority: high, medium, low"
    )

    tasks: List[str] = Field(
        default_factory=list,
        description="List of tasks required to complete the story"
    )


class Epic(BaseModel):
    """
    Represents a higher-level engineering initiative
    """

    title: str = Field(..., description="Epic title")

    description: Optional[str] = Field(
        default="",
        description="Epic description"
    )

    stories: List[Story] = Field(
        default_factory=list,
        description="Stories belonging to the epic"
    )


class Backlog(BaseModel):
    """
    Top level backlog structure generated by the AI agent
    """

    epics: List[Epic] = Field(
        default_factory=list,
        description="List of epics generated from meeting notes"
    )
